CREATE TABLE IF NOT EXISTS ANNOTATIONS (
    id               SERIAL   PRIMARY KEY,
    content          TEXT     NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PHOTOS (
    id               SERIAL   PRIMARY KEY,
    content          TEXT     NOT NULL,
    is_additional    BOOLEAN  NOT NULL DEFAULT FALSE,
    annotation_id    INTEGER  DEFAULT -1,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE ANNOTATIONS
ADD CONSTRAINT photo_id
FOREIGN KEY (id)
REFERENCES PHOTOS(id)
ON DELETE CASCADE;

ALTER TABLE PHOTOS
ADD CONSTRAINT annotation_id
FOREIGN KEY (id)
REFERENCES ANNOTATIONS(id)
ON DELETE CASCADE;
